-- Add fields for document summary, suggested questions, and quick actions to chat_conversations table
ALTER TABLE IF EXISTS chat_conversations
ADD COLUMN IF NOT EXISTS summary TEXT,
ADD COLUMN IF NOT EXISTS suggested_questions JSONB,
ADD COLUMN IF NOT EXISTS quick_actions JSONB;

-- Add comments explaining the purpose of these columns
COMMENT ON COLUMN chat_conversations.summary IS 'Document summary generated by AI';
COMMENT ON COLUMN chat_conversations.suggested_questions IS 'JSON array of suggested questions for the document';
COMMENT ON COLUMN chat_conversations.quick_actions IS 'JSON array of quick actions available for the document'; 